Order api   get
developers-bootcamp/order-manager-green pull request #17
Opened 2023-07-09 10:36 UTC by RivkaEhrenfeld

יש גם דברים שהם לא בpull request הזה ששיניתי 
אשמח את תולי לעבור עם כל api order
תודה

2023-07-11 20:24 UTC, moriyahazan requested changes

2023-07-11 20:24 UTC, moriyahazan commented on src/main/java/com/sap/ordermanegergreen/Repositories/IOrderRepository.java
> +    List<Orders> findByOrderStatusId(Pageable pageable, String companyId,String orderStatusId);
please add company name to query

2023-07-11 20:24 UTC, moriyahazan commented on src/main/java/com/sap/ordermanegergreen/Controllers/OrdersController.java
> +    @RequestMapping("/create")
remove mapping create

2023-07-11 20:24 UTC, moriyahazan commented on src/main/java/com/sap/ordermanegergreen/Controllers/OrdersController.java
> +    @RequestMapping("/update")
remove mapping

2023-07-11 20:24 UTC, moriyahazan commented on src/main/java/com/sap/ordermanegergreen/Controllers/OrdersController.java
> +    public ResponseEntity< Map<String, HashMap<Double,Integer>> >calculate(Map<String,Integer> orderItems){
this should be for specific product and quantity and currency

2023-07-11 20:24 UTC, moriyahazan commented on src/main/java/com/sap/ordermanegergreen/Services/CustomerService.java
>          return customerRepository.findAll().stream().filter(u->u.getRoleId().equals(AvailableRoles.CUSTOMER)).toList();
the checks about role should be inside query

2023-07-12 13:36 UTC, RivkaEhrenfeld commented on src/main/java/com/sap/ordermanegergreen/Repositories/IOrderRepository.java
> +    List<Orders> findByOrderStatusId(Pageable pageable, String companyId,String orderStatusId);
whty company name and not company id?

2023-07-16 09:57 UTC, RivkaEhrenfeld commented
changed things

2023-07-16 09:57 UTC, merged