the last update version
developers-bootcamp/order-manager-green pull request #25
Opened 2023-07-17 00:01 UTC by ShaniWell

2023-07-17 18:54 UTC, moriyahazan requested changes
Nice job

please review my comments and fix

2023-07-17 18:54 UTC, moriyahazan commented on src/main/java/com/sap/ordermanagergreen/controller/UserController.java
> +    @GetMapping
Please format all classes

2023-07-17 18:54 UTC, moriyahazan commented on src/main/java/com/sap/ordermanagergreen/controller/UserController.java
> +            System.out.println("💕💕 error "+e);
you should return rest response 500 in case of exception

2023-07-17 18:54 UTC, moriyahazan commented on src/main/java/com/sap/ordermanagergreen/service/UserService.java
> +        //cheak password mail telephone...
You should create new company by signup

2023-07-18 09:40 UTC, ShaniWell commented
מוריה אני קצת לא מבינה את ההערות אשמח להסבר
ממש תודה



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
18.07.23,
12:38:51

‫בתאריך יום ב׳, 17 ביולי 2023 ב-21:54 מאת ‪Moriya‬‏ <‪
***@***.***‬‏>:‬

> ***@***.**** requested changes on this pull request.
>
> Nice job
>
> please review my comments and fix
> ------------------------------
>
> In src/main/java/com/sap/ordermanagergreen/controller/UserController.java
> <https://github.com/developers-bootcamp/order-manager-green/pull/25#discussion_r1265771909>
> :
>
> > @@ -30,6 +36,36 @@ public UserController(UserService userService, JwtToken jwtToken) {
>          this.jwtToken = jwtToken;
>      }
>
> +    @GetMapping
>
> Please format all classes
> ------------------------------
>
> In src/main/java/com/sap/ordermanagergreen/controller/UserController.java
> <https://github.com/developers-bootcamp/order-manager-green/pull/25#discussion_r1265772643>
> :
>
> > @@ -30,6 +36,36 @@ public UserController(UserService userService, JwtToken jwtToken) {
>          this.jwtToken = jwtToken;
>      }
>
> +    @GetMapping
> +    @RequestMapping("/getAllUsers")
> +    public ResponseEntity<List<UserDto>> ***@***.***(defaultValue = "1") Integer page, @RequestParam(defaultValue = "5") Integer pageSize, @RequestHeader("Authorization") String token) {
> +        TokenDTO tokenDTO=JwtToken.decodeToken(token);
> +        List<UserDto> l = null;
> +        try {
> +            l = userService.getAll(tokenDTO.getCompanyId(),page,pageSize);
> +        }
> +        catch (Exception e) {
> +            System.out.println("💕💕 error "+e);
>
> you should return rest response 500 in case of exception
> ------------------------------
>
> In src/main/java/com/sap/ordermanagergreen/service/UserService.java
> <https://github.com/developers-bootcamp/order-manager-green/pull/25#discussion_r1265776270>
> :
>
> > @@ -78,16 +104,31 @@ public void add(String token, User user) {
>              throw new ObjectExistException("user name ");
>          }
>          TokenDTO tokenDTO = JwtToken.decodeToken(token);
> -        if (roleRepository.findById(tokenDTO.getRoleId()).orElse(new Role()).getName() != AvailableRoles.CUSTOMER) {
> -            user.setAuditData(new AuditData(new Date(), new Date()));
> +        //cheak password mail telephone...
>
> You should create new company by signup
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/developers-bootcamp/order-manager-green/pull/25#pullrequestreview-1533462008>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAUW6UTW3JGBFPWCEIJV3GDXQWDAFANCNFSM6AAAAAA2MHZKOQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-07-18 12:38 UTC, ShaniWell commented on src/main/java/com/sap/ordermanagergreen/service/UserService.java
> +        //cheak password mail telephone...
i do it!!
what you mean here?

2023-07-18 19:44 UTC, moriyahazan approved these changes

2023-07-18 19:47 UTC, merged