Top product api2
developers-bootcamp/order-manager-green pull request #42
Opened 2023-08-19 21:47 UTC by moriyahazan

2023-08-19 21:51 UTC, moriyahazan commented
Hi @sara1386,
Please see my updated code with spring Mongo db aggregation, (The query you sent me didn't work, I don't know why)
You can generate data by calling to fill() method I committed (copied from another team)
please generate data only via the application and not directly by the database

if everything seems ok for you please merge to main. 

thanks 
and have a nice day

2023-08-20 00:50 UTC, geniuscodes requested changes

2023-08-20 00:50 UTC, geniuscodes commented on src/main/java/com/sap/ordermanagergreen/service/GraphService.java
> +
extra line

2023-08-20 12:29 UTC, sara1386 approved these changes
it works. thanks!
and there was really an issue with the data, fill() solved it.

2023-08-20 12:36 UTC, moriyahazan commented
great
please merge to main

‫בתאריך יום א׳, 20 באוג׳ 2023 ב-15:29 מאת ‪Sara Leah‬‏ <‪
***@***.***‬‏>:‬

> ***@***.**** approved this pull request.
>
> it works. thanks!
> and there was really an issue with the data, fill() solved it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/developers-bootcamp/order-manager-green/pull/42#pullrequestreview-1585886895>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AINHFAGU6FGPFZLREWOFTMLXWH7LXANCNFSM6AAAAAA3W2FLHY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-08-20 15:08 UTC, merged